export const CREATE_EVENT_PENDING = 'CREATE_EVENT_PENDING'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'
export const CREATE_EVENT = 'CREATE_EVENT'

export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'
export const FETCH_EVENTS = 'FETCH_EVENTS'
