export const CREATE_EVENT_PENDING = 'CREATE_EVENT_PENDING'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'
export const CREATE_EVENT = 'CREATE_EVENT'
