// EVENTS

export const CREATE_EVENT_PENDING = 'CREATE_EVENT_PENDING'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE'
export const CREATE_EVENT = 'CREATE_EVENT'

export const FETCH_EVENTS_PENDING = 'FETCH_EVENTS_PENDING'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'
export const FETCH_EVENTS = 'FETCH_EVENTS'

// STRIPE

export const STRIPE_CONNECT_CALLBACK_PENDING = 'STRIPE_CONNECT_CALLBACK_PENDING'
export const STRIPE_CONNECT_CALLBACK_SUCCESS = 'STRIPE_CONNECT_CALLBACK_SUCCESS'
export const STRIPE_CONNECT_CALLBACK_FAILURE = 'STRIPE_CONNECT_CALLBACK_FAILURE'
export const STRIPE_CONNECT_CALLBACK = 'STRIPE_CONNECT_CALLBACK'

// USERS

export const FETCH_USER_INFO_PENDING = 'FETCH_USER_INFO_PENDING'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'

// TICKETS

export const FETCH_TICKET_QR_PENDING = 'FETCH_TICKET_QR_PENDING'
export const FETCH_TICKET_QR_SUCCESS = 'FETCH_TICKET_QR_SUCCESS'
export const FETCH_TICKET_QR_FAILURE = 'FETCH_TICKET_QR_FAILURE'
export const FETCH_TICKET_QR = 'FETCH_TICKET_QR'

export const FETCH_TICKETS_PENDING = 'FETCH_TICKETS_PENDING'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'
export const FETCH_TICKETS = 'FETCH_TICKETS'
